// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    ChirpActions: typeof import('./src/components/ChirpActions.vue')['default']
    FeedChirp: typeof import('./src/components/FeedChirp.vue')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    'IHeroiconsOutline:heart': typeof import('~icons/heroicons-outline/heart')['default']
    'IHeroiconsSolid:heart': typeof import('~icons/heroicons-solid/heart')['default']
    'INoto:bird': typeof import('~icons/noto/bird')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    PostChirpWidget: typeof import('./src/components/PostChirpWidget.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
  }
}

export { }
